'use strict';
const audio=document.querySelector('#audio'), list=document.querySelector('#tracks'), search=document.querySelector('#search');
let tracks=[],current=-1,category='All',shuffled=false;
const groups=['All','Black Sea Devil','Brooklyn Rap','Battle Round'];
function group(title){if(/battle|versus| vs[ .-]/i.test(title))return groups[3];if(/brooklyn|nyc|new york|street/i.test(title))return groups[2];return groups[1];}
function visible(){return tracks.map((t,i)=>({...t,index:i})).filter(t=>(category==='All'||group(t.title)===category)&&t.title.toLowerCase().includes(search.value.toLowerCase()));}
function render(){list.replaceChildren();const selection=visible();document.querySelector('#count').textContent=selection.length+' of '+tracks.length+' battle rounds';selection.forEach(t=>{const card=document.createElement('article');card.className='track'+(t.index===current?' active':'');const meta=document.createElement('span');meta.className='meta';meta.textContent='ROUND '+String(t.id).padStart(2,'0')+' / '+group(t.title);const title=document.createElement('h3');title.textContent=t.title;const button=document.createElement('button');button.textContent=t.index===current&&!audio.paused?'Ⅱ Pause':'▶ Play round';button.setAttribute('aria-label',button.textContent+' — '+t.title);button.onclick=()=>t.index===current?(audio.paused?play():audio.pause()):select(t.index,true);card.append(meta,title,button);list.append(card);});if(!selection.length){const p=document.createElement('p');p.textContent='No rounds found. Try another search or side.';list.append(p);}}
async function play(){try{await audio.play();document.querySelector('#message').textContent='';}catch(e){document.querySelector('#message').textContent='Playback could not start. Use the audio controls to try again.';}}
function select(i,start){if(!tracks[i])return;current=i;audio.src=tracks[i].url;document.querySelector('#now-title').textContent=tracks[i].title;history.replaceState(null,'','#track='+tracks[i].id);render();if(start)play();}
function step(delta){const pool=visible().map(t=>t.index);if(!pool.length)return;let next;if(shuffled&&pool.length>1){const others=pool.filter(i=>i!==current);next=others[Math.floor(Math.random()*others.length)];}else{const pos=pool.indexOf(current);next=pos<0?pool[0]:pool[(pos+delta+pool.length)%pool.length];}select(next,true);}
document.querySelector('#prev').onclick=()=>step(-1);document.querySelector('#next').onclick=()=>step(1);document.querySelector('#shuffle').onclick=e=>{shuffled=!shuffled;e.currentTarget.setAttribute('aria-pressed',shuffled);};document.querySelector('#repeat').onclick=e=>{audio.loop=!audio.loop;e.currentTarget.setAttribute('aria-pressed',audio.loop);};
document.querySelector('#share').onclick=async()=>{try{const data={title:'Devils From Black Sea Tower vs Brooklyn Rap',url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);document.querySelector('#message').textContent='Battle link copied.';}}catch(e){if(e.name!=='AbortError')document.querySelector('#message').textContent='Copy this page address to share the battle.';}};
audio.addEventListener('ended',()=>step(1));['play','pause'].forEach(event=>audio.addEventListener(event,()=>{document.body.classList.toggle('playing',!audio.paused);render();}));audio.addEventListener('error',()=>{document.querySelector('#message').textContent='This MP3 could not load. Please try another round or retry later.';document.body.classList.remove('playing');});search.addEventListener('input',render);
groups.forEach(name=>{const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed',name===category);b.onclick=()=>{category=name;document.querySelectorAll('#filters button').forEach(el=>el.setAttribute('aria-pressed',el===b));render();};document.querySelector('#filters').append(b);});
fetch('./tracks.json').then(r=>{if(!r.ok)throw new Error('manifest');return r.json();}).then(data=>{tracks=data;if(!tracks.length){document.querySelector('#count').textContent='Battle rounds dropping soon — MP3s coming to the tower.';return;}const id=Number(new URLSearchParams(location.hash.slice(1)).get('track'));select(Math.max(0,tracks.findIndex(t=>t.id===id)),false);}).catch(()=>{document.querySelector('#count').textContent='Playlist unavailable. Please reload to try again.';});
